<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_About MarketProminence_mpweb-navbar-icon-_43a834</name>
   <tag></tag>
   <elementGuidId>e4dc70ba-12b1-4982-83a1-660c44b1f87a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mpweb-navbar-icon-button-user-dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mpweb-navbar-icon-button-user-dropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81c8840b-f155-4f08-b2ea-4511bacd2beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>92ec30a1-758a-4c30-8f44-18d669696b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56a462ad-197e-4d07-9e7d-3b5e719199ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>86679028-18c5-488c-8dec-c30a2de2504d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cf25b3e1-45eb-4596-8499-c2eacbdb6afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link dropdown-toggle show</value>
      <webElementGuid>fcdf2eac-61b8-4877-8100-07842c848a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lynch, Emmettf (Administrator: System)</value>
      <webElementGuid>2ff564d5-4b21-4d0f-9f93-c0b559575679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6d9dc6a8-3a28-4df7-873b-a09d68be0d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-navbar-icon-button-user-dropdown</value>
      <webElementGuid>5f76857d-bdd2-4296-881c-7c60ba84e5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-navbar-icon-button-user-dropdown&quot;)</value>
      <webElementGuid>dd90b203-94e7-4001-b007-d38c1de80ed7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mpweb-navbar-icon-button-user-dropdown']</value>
      <webElementGuid>2410ecac-8e5e-48d6-8b66-be604c7e8723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About MarketProminence'])[1]/following::a[1]</value>
      <webElementGuid>292f9e1d-97cb-41b6-b64d-72e8426da2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dedupe'])[1]/following::a[3]</value>
      <webElementGuid>3d86a14a-6808-4ad9-a56c-a4296df4a673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Break Time'])[1]/preceding::a[1]</value>
      <webElementGuid>5181a77c-10e1-4e28-8b39-9ab77ca878d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preference'])[1]/preceding::a[2]</value>
      <webElementGuid>2f7b945f-dc8f-42d2-88a2-df1fbc82ab9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>a2b94cec-acdc-4533-a7dc-2271d3b7dbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>b337211e-02d0-447e-90ff-25f6eaa2fdf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Lynch, Emmettf (Administrator: System)' and @href = '#' and @id = 'mpweb-navbar-icon-button-user-dropdown']</value>
      <webElementGuid>e5836c7a-16ce-4151-a743-379da92b66cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
