<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MarketProminence_mpweb-navbar-icon-button_1cdd27</name>
   <tag></tag>
   <elementGuidId>ff7fbb47-8cbd-4b9c-a780-07695f8999fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mpweb-navbar-icon-button-windows-dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mpweb-navbar-icon-button-windows-dropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a490583-dfde-4002-b559-a7a1e35c87f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>3d0f81ab-4fcd-4f76-914d-22d0393a123c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Windows</value>
      <webElementGuid>d367281f-9922-43cd-8432-ed545c53c3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aa4814a4-082f-4437-b2fc-4be7ee090538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>0c40ab9f-e1ad-4edb-ab9e-de21b579012f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>24ae6ca0-7c91-40a6-bf26-c7e0557b0281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle nav-link show</value>
      <webElementGuid>b978d188-3605-4a18-8665-2d7ca7a6b5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>857d7670-0aa5-46e9-8b2d-d276d952931b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-navbar-icon-button-windows-dropdown</value>
      <webElementGuid>81ef2225-02fb-4ffe-a158-a5d4b5b42c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-navbar-icon-button-windows-dropdown&quot;)</value>
      <webElementGuid>48bf6bf1-c983-4d10-9534-7221858d9a10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mpweb-navbar-icon-button-windows-dropdown']</value>
      <webElementGuid>dce53b35-822f-4f9c-a750-e4c8286a6adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MarketProminence'])[1]/following::a[4]</value>
      <webElementGuid>60a263c3-3f4d-429f-bb07-9994b0f94d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setup'])[1]/preceding::a[1]</value>
      <webElementGuid>467ba34a-8eca-46fd-8d04-545e0087a6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queue Manager'])[1]/preceding::a[2]</value>
      <webElementGuid>7c26a4ee-5d86-4dba-930b-4fc364ef6024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>f51b071c-8b6d-4e7e-8f2e-b49a721d9f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>ebbe1aa7-dbac-49d2-90fb-ab5dc6556102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Windows' and @href = '#' and @id = 'mpweb-navbar-icon-button-windows-dropdown']</value>
      <webElementGuid>46ef82dc-5ef2-4690-b22b-115b6d250586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queue Manager'])[1]/preceding::a[1]</value>
      <webElementGuid>2a1a3ab2-e95f-4447-a484-dbec68100ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setup'])[1]/preceding::a[2]</value>
      <webElementGuid>519b1946-a8ad-4182-8f39-7aa0e005a602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
