<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Applytocheckbox2</name>
   <tag></tag>
   <elementGuidId>92f1e510-3ca7-4d6b-ba33-7a2b997c9722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id=&quot;mpweb-setup-setupaffiliation-setupaffiliation-full-editable-grid-applyto-selected&quot;])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id=&quot;mpweb-setup-setupaffiliation-setupaffiliation-full-editable-grid-applyto-selected&quot;])[2]</value>
      <webElementGuid>1b217efa-8bdb-487d-8f7f-318314c8884a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
