<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Copy</name>
   <tag></tag>
   <elementGuidId>2d057ad3-d336-4e9a-b056-23b54f5d9be1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mpweb-setup-setupaffiliation-setupaffiliation-button-copy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mpweb-setup-setupaffiliation-setupaffiliation-button-copy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29ab7431-63c5-4d77-af04-4650d76567ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f19a92b9-da07-4754-b87d-c67496b15403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn ng-star-inserted</value>
      <webElementGuid>851906b3-170d-439c-b0c6-3d2b413cf27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-setup-setupaffiliation-setupaffiliation-button-copy</value>
      <webElementGuid>29b005e6-c199-40df-8986-73d5a92af438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copy</value>
      <webElementGuid>b7e260ee-47fa-4510-bc4c-d3a7472cf52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-setupaffiliation-setupaffiliation-button-copy&quot;)</value>
      <webElementGuid>420c2d74-ac93-402c-a6dd-b0701a7c2349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mpweb-setup-setupaffiliation-setupaffiliation-button-copy']</value>
      <webElementGuid>bee34004-02b8-4904-8718-9c04cbb9c698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M03 | M05'])[2]/following::button[1]</value>
      <webElementGuid>ef17ed87-74b2-4062-a36f-09156df6f9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assigned Programs'])[4]/following::button[1]</value>
      <webElementGuid>e6fd60f6-446e-4ffa-a108-b5aeda7b252c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::button[1]</value>
      <webElementGuid>77860b7d-b926-4543-8db0-5ee94aaf8e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mpweb-setup-setupaffiliation-setupaffiliation-button-copy', '&quot;', ')')])[1]/preceding::button[2]</value>
      <webElementGuid>33a533cf-78c9-4f8a-9ae7-3b5ae9f3b754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copy']/parent::*</value>
      <webElementGuid>c9bf5c81-3491-489c-94c1-6d22bb222f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//setup-copy-card/custom-card/div/div[2]/action-info-bar/div/div/div/mp-editor-button-bar/div/button</value>
      <webElementGuid>44005385-b32a-4832-8346-7bfda77830d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'mpweb-setup-setupaffiliation-setupaffiliation-button-copy' and (text() = 'Copy' or . = 'Copy')]</value>
      <webElementGuid>9e1a324a-dfc8-4f40-8d25-595168d64fa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
