<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yes</name>
   <tag></tag>
   <elementGuidId>759aa945-8623-4338-8c5c-af4163facd72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mp-message-box-contents.ng-tns-c38-22.ng-star-inserted > action-info-bar > div.action-info-bar-container > div.main-row > div.button-bar > mp-editor-button-bar > div.editor-button-bar-wrapper > button.btn.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b845a222-0518-4c90-833f-fe4af8fc7a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38172c30-4d96-4c84-a925-da25253febf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn ng-star-inserted</value>
      <webElementGuid>5400abea-ce89-4a1b-801e-2c5c2979ad75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>55824ad9-c66e-494f-bbf1-88779575924b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kendo-dialog-content-495789&quot;)/mp-message-box-contents[@class=&quot;ng-tns-c38-22 ng-star-inserted&quot;]/action-info-bar[1]/div[@class=&quot;action-info-bar-container&quot;]/div[@class=&quot;main-row&quot;]/div[@class=&quot;button-bar&quot;]/mp-editor-button-bar[1]/div[@class=&quot;editor-button-bar-wrapper&quot;]/button[@class=&quot;btn ng-star-inserted&quot;]</value>
      <webElementGuid>2f3e95af-b69a-48cc-888b-5b47c755313d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>09cc2c1a-2ae8-4845-aae2-f2c5d61c2498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kendo-dialog-content-495789']/mp-message-box-contents/action-info-bar/div/div/div/mp-editor-button-bar/div/button</value>
      <webElementGuid>6a82c1b1-9be4-454e-b3ef-8aff6a4ee9a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Warning'])[1]/following::button[2]</value>
      <webElementGuid>967d0a02-18eb-4cbe-bfe3-6695a3edc693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[2]</value>
      <webElementGuid>e87c544c-3497-4f17-92e8-22ed8de7432b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>d87bef51-9741-4c4a-b3c9-9410269f04d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MarketProminence 1.5.105'])[1]/preceding::button[2]</value>
      <webElementGuid>34fdd70a-643a-42dd-96c1-e6b180e8b537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>fbfdf432-909c-4f54-bed8-8f99c601b84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mp-message-box-contents/action-info-bar/div/div/div/mp-editor-button-bar/div/button</value>
      <webElementGuid>b32f4062-09c4-406e-9ac7-68d2bf7ec0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>07f08a36-ce02-4377-b23d-7bccce0c9695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
