<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_G00065182648_1</name>
   <tag></tag>
   <elementGuidId>30ba5f3d-c037-4cdc-81d0-7a2957d84c98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[2]/following::div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf9103b5-93df-4622-9701-41d4f58c3a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formatted-field-value</value>
      <webElementGuid>2bcc1539-6dfd-4220-8eb3-65c08e1afbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>G00065182648</value>
      <webElementGuid>3ed80426-f6a5-4ca3-99ad-a752e5fb26f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>G00065182648</value>
      <webElementGuid>7c6322c5-6dd9-4515-862b-69790f111d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-4&quot;]/app-root[1]/div[@class=&quot;app-component-container&quot;]/div[@class=&quot;router-outlet-container&quot;]/setup-canvas[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;setup-canvas-container&quot;]/kendo-splitter[@class=&quot;splitter-container k-splitter k-splitter-flex k-splitter-horizontal&quot;]/kendo-splitter-pane[@class=&quot;k-pane k-scrollable&quot;]/div[@class=&quot;pane-content m-2px ng-star-inserted&quot;]/action-card[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card-container&quot;]/custom-card[1]/div[@class=&quot;custom-card-container ng-star-inserted&quot;]/div[@class=&quot;custom-card-grid-form-container&quot;]/kendo-splitter[@class=&quot;splitter-container k-splitter k-splitter-flex k-splitter-vertical ng-star-inserted&quot;]/kendo-splitter-pane[@class=&quot;grid-container-splitter k-pane k-scrollable&quot;]/div[@class=&quot;custom-data-view-container ng-star-inserted&quot;]/custom-data-view[1]/div[@class=&quot;custom-data-view-container&quot;]/custom-data-view-editor[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;custom-data-view-editor-container ng-star-inserted&quot;]/mp-input-container[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mp-input-container-wrapper wrapper-normal ng-star-inserted&quot;]/div[@class=&quot;input-container width-100-pct ng-star-inserted&quot;]/table[@class=&quot;table-input-container-wrapper&quot;]/tr[1]/td[1]/div[@class=&quot;input-switch-container&quot;]/mp-read-only-input[1]/div[@class=&quot;not-extended ng-star-inserted&quot;]/div[@class=&quot;data-container&quot;]/div[@class=&quot;formatted-field-value&quot;]</value>
      <webElementGuid>c2824e0a-738c-4fb6-a4bf-62d2a3d6c8b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[2]/following::div[2]</value>
      <webElementGuid>c854d601-e326-4413-95dc-08fb6c01915a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secondary'])[2]/following::div[10]</value>
      <webElementGuid>c5c73cdc-e7c8-4f98-b8ff-74f2d1f598c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site'])[2]/preceding::div[1]</value>
      <webElementGuid>d5ba54b6-ab1c-4737-b38e-b8768dd4affb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EP03-1'])[210]/preceding::div[1]</value>
      <webElementGuid>a2d27221-5c0d-4721-a990-33946e5e7731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mp-input-container[4]/div/div/table/tr/td/div/mp-read-only-input/div/div[2]/div</value>
      <webElementGuid>cf0bb10c-9006-4841-92e5-aca616995b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'G00065182648' and (text() = 'G00065182648' or . = 'G00065182648')]</value>
      <webElementGuid>63505b0c-eb70-4c5c-a1c1-bcbfffc639bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
