<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contains_action-icon-is-enabled fa fa-fw _a6b016</name>
   <tag></tag>
   <elementGuidId>b0e08f58-aa76-4283-b837-4c6527486d74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.action-icon-is-enabled.fa.fa-fw.fa-toggle-on.toolbar-icon.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>788db33d-93d5-4943-b49f-8d3c3d477a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action-icon-is-enabled fa fa-fw fa-toggle-on toolbar-icon ng-star-inserted</value>
      <webElementGuid>95f4b8a6-375c-4c0c-8a7a-0f04edc61386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>131b431b-c187-4503-ab95-5a2746e84436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-grid7-r2c0&quot;)/i[@class=&quot;action-icon-is-enabled fa fa-fw fa-toggle-on toolbar-icon ng-star-inserted&quot;]</value>
      <webElementGuid>7d9a7630-71e5-4abf-9850-832e6d628ab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='k-grid7-r2c0']/i[4]</value>
      <webElementGuid>8b498207-72ba-4775-89b6-e3bac40575aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[4]</value>
      <webElementGuid>6b6a62ad-f43f-4dab-bec2-dae271d95925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Active']</value>
      <webElementGuid>b153ec75-d8ca-4597-be49-0c422b40390b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
