<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contains_copyFrom-selected-col-radio-0</name>
   <tag></tag>
   <elementGuidId>52e92323-4ad3-4438-8fcc-00047f6acb26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mpweb-setup-setupaffiliation-setupaffiliation-full-editable-grid-copyfrom-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mpweb-setup-setupaffiliation-setupaffiliation-full-editable-grid-copyfrom-selected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b682a809-ab08-42ec-a0e3-a131be285108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable-control ng-star-inserted</value>
      <webElementGuid>9a5bd23b-1b24-4dff-a925-8d7aa848db7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c78a38f6-2c35-469a-b9c5-c407a476bd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-setup-setupaffiliation-setupaffiliation-full-editable-grid-copyfrom-selected</value>
      <webElementGuid>9e0f40d5-edc0-422c-9d70-7c2c78f96db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>copyFrom-selected-col-radio-0</value>
      <webElementGuid>2cca9489-5079-475a-b76b-7df1a42161da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60929d46-b838-47df-9017-bb83328c20f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-setupaffiliation-setupaffiliation-full-editable-grid-copyfrom-selected&quot;)</value>
      <webElementGuid>e34b73b5-2d62-4dfc-ab2d-9ac8b8cd3fb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mpweb-setup-setupaffiliation-setupaffiliation-full-editable-grid-copyfrom-selected']</value>
      <webElementGuid>0de01680-ee1c-4d50-b8ca-53d18bf37075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='mpweb-setup-setupaffiliation-setupaffiliation-full-editable-grid-copyfrom-grid']/div/kendo-grid-list/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>4f6959e7-3222-4bdb-ae0a-db839ec77b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/mp-input-container/div/div/table/tr/td/div/full-editable-grid/div/div[2]/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>dec0a34c-233e-4dd5-a6e3-db8e8f05bb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'mpweb-setup-setupaffiliation-setupaffiliation-full-editable-grid-copyfrom-selected' and @name = 'copyFrom-selected-col-radio-0']</value>
      <webElementGuid>77a4690c-8205-4163-817d-ed52b9d870f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
