<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_M03_assignedPrograms-SELECTED-row-3-col-0</name>
   <tag></tag>
   <elementGuidId>7fc7d49d-e359-4ef5-bab0-41f009416d0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a08349c-24bc-49f0-be3e-914acb47268f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable-control ng-star-inserted</value>
      <webElementGuid>d16d6401-d41e-4287-945e-5da04049978f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b25004d3-0961-4c14-9ac1-2bfd2768350a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected</value>
      <webElementGuid>a58cde45-d091-4a53-bc94-dfd894e57533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignedPrograms-SELECTED-row-3-col-0</value>
      <webElementGuid>c4b18066-1289-4e03-acd4-2fca79451445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-grid&quot;)/div[@class=&quot;k-grid-aria-root&quot;]/kendo-grid-list[@class=&quot;k-grid-container ng-star-inserted&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[@class=&quot;k-grid-table-wrap&quot;]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;k-alt ng-star-inserted&quot;]/td[@class=&quot;k-touch-action-auto cursor-default text-center NO-boolean ng-star-inserted&quot;]/input[@id=&quot;mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected&quot;]</value>
      <webElementGuid>1836ba63-4a86-412e-a49c-117622044c81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected'])[4]</value>
      <webElementGuid>a58b3d3a-07c7-49cb-b687-b7791c55bf59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-grid']/div/kendo-grid-list/div/div/table/tbody/tr[4]/td/input</value>
      <webElementGuid>4b7ba551-151f-4b5b-91c4-27f12c08e303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>7f2d71c6-aced-4ce5-ba1f-1c1a7c2f55bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected' and @name = 'assignedPrograms-SELECTED-row-3-col-0']</value>
      <webElementGuid>8a75f2da-86c4-411f-b3f9-b9f50c38be98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
