<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contains_assignedPrograms-SELECTED-ro_1fd6e7</name>
   <tag></tag>
   <elementGuidId>ed4d6e0f-57a8-46c7-aef4-d605a797ecf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ab31da5-ba8a-4cb6-b414-b7ef9911d594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable-control ng-star-inserted</value>
      <webElementGuid>140aa741-e526-4b35-ab6f-559e7b6587fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>291972f3-7427-4118-8ad4-828e4edea2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected</value>
      <webElementGuid>161d8d84-0000-4167-a7f1-0b0dd98d04c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignedPrograms-SELECTED-row-0-col-0</value>
      <webElementGuid>4d1746bb-4d29-480a-804c-797560a589d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-grid&quot;)/div[@class=&quot;k-grid-aria-root&quot;]/kendo-grid-list[@class=&quot;k-grid-container ng-star-inserted&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[@class=&quot;k-grid-table-wrap&quot;]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;k-touch-action-auto cursor-default text-center NO-boolean ng-star-inserted&quot;]/input[@id=&quot;mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected&quot;]</value>
      <webElementGuid>2b5440cb-385c-4496-94f0-f09f3a598b1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected']</value>
      <webElementGuid>0ef27fae-40a5-4ed3-8c0e-b8930cb013bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-grid']/div/kendo-grid-list/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>d811faf8-0b7c-4205-9e56-20ca29ddf54d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>67297fc5-bc0d-4052-b9da-09556bb76a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected' and @name = 'assignedPrograms-SELECTED-row-0-col-0']</value>
      <webElementGuid>5c4295b2-b519-4337-8fbf-6789916d2dfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
