<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Secondary_secondary</name>
   <tag></tag>
   <elementGuidId>cf730b8a-3492-47a0-805e-0ef5ac282728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-type-9ca10e7a-a228-41e9-a49f-08e15a2b6e2b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-type-9ca10e7a-a228-41e9-a49f-08e15a2b6e2b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>211e2856-4d03-4bd3-b08c-25a90e0c590e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-input width-100-pct</value>
      <webElementGuid>5ce56a26-3d0d-4a1a-a9e5-c1ec27677889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-type-9ca10e7a-a228-41e9-a49f-08e15a2b6e2b</value>
      <webElementGuid>c39cf5c0-3e09-47ea-ad8f-b921aae4d179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>4fa1ab60-a654-4b7f-a1c6-eb3b29437aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>594a29a0-26a8-44ac-821f-dc8e1f0d3125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>cb056628-d694-4942-a4aa-952f00ad1c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-type-9ca10e7a-a228-41e9-a49f-08e15a2b6e2b&quot;)</value>
      <webElementGuid>d5a2f980-cdab-4518-9ac6-f7ded1dd5f45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-type-9ca10e7a-a228-41e9-a49f-08e15a2b6e2b']</value>
      <webElementGuid>5d890b57-8353-44bd-93a1-79f2bd0aaf57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mpweb-setup-setupaction-input-secondary']/input</value>
      <webElementGuid>b57b9a8c-f17a-4d6d-a83f-ae0c1455bb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>290efae5-f81f-410f-bdf4-986e40b9c91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-type-9ca10e7a-a228-41e9-a49f-08e15a2b6e2b' and @name = 'secondary' and @type = 'text']</value>
      <webElementGuid>507e44d4-6a00-4dce-9300-c606e905415b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
