<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary_action</name>
   <tag></tag>
   <elementGuidId>ec362216-58e5-44ea-ba7d-f2b65c8f80c7</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-4aa542c3-5746-463a-b2b8-a1efef1fd3ff</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//kendo-combobox[@id='mpweb-setup-setupaction-combo-box-primary']/kendo-searchbar/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'k-4aa542c3-5746-463a-b2b8-a1efef1fd3ff']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5bd723b-142d-4d3d-a9e9-7f78366435af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>86d97bc1-06b6-4bbb-9da4-15eb156b44f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ea613031-b9d6-438b-a353-7d79a7e26414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ccf53b16-937a-439e-b914-97bd21438907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner</value>
      <webElementGuid>2be4fae9-17c1-4586-b344-4a519cc05c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-4aa542c3-5746-463a-b2b8-a1efef1fd3ff</value>
      <webElementGuid>c5f86645-72f8-4cfb-a6da-ed69170a7bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5c2478c7-849a-440f-ae61-f2240f1d9744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>01f4a482-f01f-4986-94ed-d1c298916a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>267482f0-22ea-41fd-a14a-2780276e1988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b65cc266-c77c-48c0-8519-09375a6fe6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cdd4fa2a-9f07-42ed-aef6-7d24db036093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2ae8af3e-4cb5-41c4-928f-8e5b9c6d31f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>09e84ba5-50e3-4504-bf46-d2417288b3ff</value>
      <webElementGuid>c5661270-fed5-40ed-93a4-b6f235389b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-4aa542c3-5746-463a-b2b8-a1efef1fd3ff&quot;)</value>
      <webElementGuid>92dcb329-6a67-4072-ae71-3d5ac1a8f8b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-4aa542c3-5746-463a-b2b8-a1efef1fd3ff']</value>
      <webElementGuid>0a2b6ba8-1812-459b-a597-7ea742483fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-combobox[@id='mpweb-setup-setupaction-combo-box-primary']/kendo-searchbar/input</value>
      <webElementGuid>e3885f77-e6c1-4f3b-9739-84ba7f26384e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-searchbar/input</value>
      <webElementGuid>5ffe12b6-5df8-4d08-9cf2-60bd62deffc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-4aa542c3-5746-463a-b2b8-a1efef1fd3ff']</value>
      <webElementGuid>e08b2a24-ae8e-4c4d-8dca-4125410fa4da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
