<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lan_assignedPrograms-SELECTED-row-2-col-0</name>
   <tag></tag>
   <elementGuidId>ab6c656b-a13d-47b1-923a-fe44bdf5a886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1544fc2-a3a0-4627-a14b-85bc6776cf9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable-control ng-star-inserted</value>
      <webElementGuid>6ec0912b-14be-4174-b10a-5417564bf86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f273689b-4875-4705-a378-f68d57efdec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected</value>
      <webElementGuid>33ded748-f881-499f-b5dd-e930ef268924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignedPrograms-SELECTED-row-2-col-0</value>
      <webElementGuid>fbccf099-57d1-4f01-9c03-d60b18baad4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-grid&quot;)/div[@class=&quot;k-grid-aria-root&quot;]/kendo-grid-list[@class=&quot;k-grid-container ng-star-inserted&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[@class=&quot;k-grid-table-wrap&quot;]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;k-touch-action-auto cursor-default text-center NO-boolean ng-star-inserted&quot;]/input[@id=&quot;mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected&quot;]</value>
      <webElementGuid>babb717a-e55b-4f6b-86ab-f87bf0fabe1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected'])[3]</value>
      <webElementGuid>4ce042b7-9d4a-4bdf-9e75-695c9d1785b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-grid']/div/kendo-grid-list/div/div/table/tbody/tr[3]/td/input</value>
      <webElementGuid>a62bc478-6d87-4a37-81c4-e8ff84968b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>82305f86-4d55-4a47-aebd-8a608ea5ae43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected' and @name = 'assignedPrograms-SELECTED-row-2-col-0']</value>
      <webElementGuid>2f0f752a-dc5e-40be-82b1-2bae1e64bbd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
