<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KL0_assignedPrograms-SELECTED-row-1-col-0</name>
   <tag></tag>
   <elementGuidId>d03a6452-c5d5-45c0-9ee1-65af58bf78b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.k-alt.ng-star-inserted > td.k-touch-action-auto.cursor-default.text-center.NO-boolean.ng-star-inserted > #mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7c0c122-9c16-42f3-80e9-d2f6e6f01265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable-control ng-star-inserted</value>
      <webElementGuid>990b0531-a0aa-468a-b016-fee87304e629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>293f4e2b-39a7-4e4d-85c2-84f29290119b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected</value>
      <webElementGuid>1275bbfd-6734-4353-8228-d660a1dab249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignedPrograms-SELECTED-row-1-col-0</value>
      <webElementGuid>5ec8d2a4-de7c-42d4-858e-931ad5a6fb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-grid&quot;)/div[@class=&quot;k-grid-aria-root&quot;]/kendo-grid-list[@class=&quot;k-grid-container ng-star-inserted&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[@class=&quot;k-grid-table-wrap&quot;]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;k-alt ng-star-inserted&quot;]/td[@class=&quot;k-touch-action-auto cursor-default text-center NO-boolean ng-star-inserted&quot;]/input[@id=&quot;mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected&quot;]</value>
      <webElementGuid>028b9511-54b5-4b17-86be-634a7c39f8a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected'])[2]</value>
      <webElementGuid>ecca6c8a-b8e2-4891-b46e-e645517d8750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-grid']/div/kendo-grid-list/div/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>c1277d97-a34b-4e81-a053-7a5378c1c6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>f2d95f15-d22c-4371-bfc0-5605a96ea294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected' and @name = 'assignedPrograms-SELECTED-row-1-col-0']</value>
      <webElementGuid>20c06676-766d-422f-88c3-734eecf4f6e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
