<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Secondary_affiliation</name>
   <tag></tag>
   <elementGuidId>a0296259-bcf4-4dc1-9f06-da65fb85f504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-type-5d889c67-919e-49b3-a3ac-cc7d54e2a4aa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d95b9604-e54e-48d1-96b7-8ae6bc33f091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-input width-100-pct</value>
      <webElementGuid>ba258b36-42aa-487a-b415-34a378da83fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-type-5d889c67-919e-49b3-a3ac-cc7d54e2a4aa</value>
      <webElementGuid>6713c8a1-d682-4f3c-83eb-f4c606e4256f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>a1c51a9a-2c49-41c7-a15f-4425a946ee8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>460fdb48-1ab9-4a8c-b651-5671fe9f1289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>40b6dcd6-4417-4446-a806-0da0222b7908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-type-5d889c67-919e-49b3-a3ac-cc7d54e2a4aa&quot;)</value>
      <webElementGuid>40beebec-3a1b-41d4-a998-ba6449cdb72c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-type-5d889c67-919e-49b3-a3ac-cc7d54e2a4aa']</value>
      <webElementGuid>f8efb268-d4d2-4042-98c6-46209044474f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mpweb-setup-setupaffiliation-input-secondary']/input</value>
      <webElementGuid>f06ef219-17d3-40f0-8325-8d377ec45f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>4619af7a-1b00-4c1f-87b1-e5e1447653f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-type-5d889c67-919e-49b3-a3ac-cc7d54e2a4aa' and @name = 'secondary' and @type = 'text']</value>
      <webElementGuid>3cbf9114-2d6e-4855-9ad1-97bb572080ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-type-e7b72004-277f-43c5-bd7a-1b8f23bead2b']</value>
      <webElementGuid>7d444a24-5fae-4eb0-83c8-3137d90150ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mpweb-setup-setupaction-input-secondary']/input</value>
      <webElementGuid>788502e0-667f-4913-9350-9fa60f0d3773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-type-e7b72004-277f-43c5-bd7a-1b8f23bead2b' and @name = 'secondary' and @type = 'text']</value>
      <webElementGuid>f8674db1-ec03-4d38-a9af-c2d7e4907dd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
