<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary_affiliation</name>
   <tag></tag>
   <elementGuidId>e05a94c9-880e-4260-b983-1ae5e50bc05b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-9c80b1f5-d3cb-4509-81f4-c19b9192a35c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//kendo-combobox[@id='mpweb-setup-setupaffiliation-combo-box-primary']/kendo-searchbar/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1aaf4222-2e05-40b7-997d-25b5ae6f8543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2885bbd4-4415-405b-ae75-2bab872d9613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>316384a7-f66c-46c8-b1fc-ff16edbab42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0f5e78c0-c292-4cf8-8109-9d639d81fd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner</value>
      <webElementGuid>35f7017a-3abd-49f9-af50-a21f134e0994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-9c80b1f5-d3cb-4509-81f4-c19b9192a35c</value>
      <webElementGuid>51a1efdc-4fea-4770-bea2-087927591aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6620af78-56df-46cc-9057-f873da6590f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>550b734b-eea9-4a94-8d03-07c2f0d651f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>645eaf9e-889a-4274-b101-03a652f66eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7eaf2243-b1cc-4389-855c-0eabf223b5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>19abdf7e-9fd6-4022-9232-41f94b4e65d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4cd5d777-9534-4962-9e55-322104ecfcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>7e7a1626-7230-4a14-8433-9894f5203c93</value>
      <webElementGuid>2b3cd94c-fc3d-47b8-a59f-d5691a2732bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-9c80b1f5-d3cb-4509-81f4-c19b9192a35c&quot;)</value>
      <webElementGuid>cb32ddc2-3b66-4013-a050-7fca6d22617d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-9c80b1f5-d3cb-4509-81f4-c19b9192a35c']</value>
      <webElementGuid>e2f390a4-1d33-4093-a3c1-f75d92dfd0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-combobox[@id='mpweb-setup-setupaffiliation-combo-box-primary']/kendo-searchbar/input</value>
      <webElementGuid>48ca252c-eb08-41e0-a9ab-1563acafbcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-searchbar/input</value>
      <webElementGuid>da474463-edfc-4b0c-97e4-1eb6164f30c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-9c80b1f5-d3cb-4509-81f4-c19b9192a35c']</value>
      <webElementGuid>0096acc2-0440-4d9b-b9a4-8a05ad8b8fa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
