<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_M05_assignedPrograms-SELECTED-row-4-col-0</name>
   <tag></tag>
   <elementGuidId>9b046f35-827f-41af-b28f-8af698dbdfbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a62d4ee-1935-4ad2-8798-b12c4bffa300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable-control ng-star-inserted</value>
      <webElementGuid>3dd6df7e-b5ba-4a53-a881-ce463e3f3d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bb593134-29a3-4786-808b-8acdd95b54cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected</value>
      <webElementGuid>da35038c-e302-443c-ad2e-ff7aabbe4878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignedPrograms-SELECTED-row-4-col-0</value>
      <webElementGuid>de0f7029-59ab-4568-96d1-8f68a33f564d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-grid&quot;)/div[@class=&quot;k-grid-aria-root&quot;]/kendo-grid-list[@class=&quot;k-grid-container ng-star-inserted&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[@class=&quot;k-grid-table-wrap&quot;]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;k-touch-action-auto cursor-default text-center NO-boolean ng-star-inserted&quot;]/input[@id=&quot;mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected&quot;]</value>
      <webElementGuid>94d5984c-b12f-4c1c-99ed-ca05213258fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected'])[5]</value>
      <webElementGuid>3da63374-0694-401b-ac92-fb402d598c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-grid']/div/kendo-grid-list/div/div/table/tbody/tr[5]/td/input</value>
      <webElementGuid>8bf0d596-4495-4f8a-a409-29db041418a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/input</value>
      <webElementGuid>a06ee937-17b6-4253-a65c-31b0ec6e7ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mpweb-setup-setupaffiliation-full-editable-grid-assignedprograms-selected' and @name = 'assignedPrograms-SELECTED-row-4-col-0']</value>
      <webElementGuid>18d10e06-d0e9-4c4c-802e-7a75cf1ab21e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
