<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_testing</name>
   <tag></tag>
   <elementGuidId>78767d14-6137-46c5-9af5-48f0bd8e1184</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='test by apankaj'])[1]/following::li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#931edfb9-526d-445f-ad06-e36feb8427c6-testing</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b2fb371a-6b45-4de6-8fce-d672e49efcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b0df45f3-e566-446e-b0c6-4735af14a02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item ng-star-inserted</value>
      <webElementGuid>655ce88e-a6cc-4cfa-a2fe-202b0af36bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>931edfb9-526d-445f-ad06-e36feb8427c6-testing</value>
      <webElementGuid>4af6fae1-d1fd-4d44-85eb-c6e2643a75e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>20243757-c2af-4538-b5bd-6395cf824b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>71</value>
      <webElementGuid>1227b054-040c-4963-88fb-3baef7f28e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>testing</value>
      <webElementGuid>8640bd23-e463-4486-ac22-c67ce5f12d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;931edfb9-526d-445f-ad06-e36feb8427c6-testing&quot;)</value>
      <webElementGuid>36a1413e-adc4-4864-bd44-e9dc367fbb6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='931edfb9-526d-445f-ad06-e36feb8427c6-testing']</value>
      <webElementGuid>b5c11cca-6a18-463f-97e7-a195e19ba87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='09e84ba5-50e3-4504-bf46-d2417288b3ff']/li[72]</value>
      <webElementGuid>65ad6f5a-9492-407e-9fc3-301071c66984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test by apankaj'])[1]/following::li[1]</value>
      <webElementGuid>51f9f34e-26ca-4672-a385-e37fd60fcdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[114]/following::li[2]</value>
      <webElementGuid>20f273a3-d467-4843-9388-4afd6ca0f986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[1]/preceding::li[1]</value>
      <webElementGuid>463cab41-851f-4331-b5d5-b160f11a05a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[72]</value>
      <webElementGuid>ac125af1-d66a-4901-b3a0-50c4c00805ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '931edfb9-526d-445f-ad06-e36feb8427c6-testing' and (text() = 'testing' or . = 'testing')]</value>
      <webElementGuid>250d6a8d-f07f-4109-a578-a58bc331f9e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
