<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_test</name>
   <tag></tag>
   <elementGuidId>4126d09b-2352-41f5-ba5d-a2544efb5815</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#71531486-9a05-4462-91c8-33510cb03836-test</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='71531486-9a05-4462-91c8-33510cb03836-test']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8503b1a8-6479-4a59-aa9c-6eb4bae5f020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8e7d38b7-27c1-49de-b11d-3ea15265bbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item ng-star-inserted</value>
      <webElementGuid>329e7445-534b-4ff6-bb90-2eaf24446ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>71531486-9a05-4462-91c8-33510cb03836-test</value>
      <webElementGuid>48480eee-ab73-4d7b-8d0a-953e097898f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>87322e41-0443-4a8d-8a07-6343e5d54575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>67</value>
      <webElementGuid>6fcf2674-6ff9-457c-b904-ceffdd056a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>53a17443-c3df-46b6-b90f-dc90558295af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;71531486-9a05-4462-91c8-33510cb03836-test&quot;)</value>
      <webElementGuid>801f1d54-0359-4424-bf36-38760b78ad25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='71531486-9a05-4462-91c8-33510cb03836-test']</value>
      <webElementGuid>e6343e67-7acc-4dd7-8d38-6ba73b862c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='a9da58b2-7e57-4fa0-9ea5-2988dfdd24d5']/li[68]</value>
      <webElementGuid>86ef1a74-ebe3-42b2-bf70-46088b6d7377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pk1'])[3]/following::li[1]</value>
      <webElementGuid>bba70a2d-0434-4a37-9e35-dbe8e0608fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dd'])[5]/following::li[2]</value>
      <webElementGuid>4033e697-dc0b-469d-bd3e-fc3d2e5f6818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test by apankaj'])[2]/preceding::li[1]</value>
      <webElementGuid>0800d128-41ba-49c1-a9e7-ced9e993571b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[68]</value>
      <webElementGuid>deb7df8b-50ec-407d-9633-e702cbaeb428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '71531486-9a05-4462-91c8-33510cb03836-test' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>dfc9a586-bd44-4cbe-932f-bbe6352e8ab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
