<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Records  2</name>
   <tag></tag>
   <elementGuidId>9f32acf3-df88-4333-adb6-b4c344af57ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.badge</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//kendo-grid[@id='mpweb-setup-setupaffiliation-grid']/kendo-grid-toolbar/div[3]/badge/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5851bc38-fd2c-4e17-aaba-3524391cf1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge</value>
      <webElementGuid>9280e2b6-bc59-4dd3-9732-6b3c040864bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>There are 2 records displayed in the grid below.</value>
      <webElementGuid>f35f697d-2a07-42e7-a652-28ad9334e1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Records : 2</value>
      <webElementGuid>f9c1fa16-a27b-4e6d-a97b-577122806d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-setupaffiliation-grid&quot;)/kendo-grid-toolbar[@class=&quot;k-toolbar k-grid-toolbar ng-star-inserted&quot;]/div[@class=&quot;toolbar-icon pos-abs-right-5px align-top mr-3 ng-star-inserted&quot;]/badge[1]/span[@class=&quot;badge&quot;]</value>
      <webElementGuid>13ac9676-0bbb-4519-967f-768048ce5754</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='mpweb-setup-setupaffiliation-grid']/kendo-grid-toolbar/div[3]/badge/span</value>
      <webElementGuid>b00532d6-6689-475c-b401-e014e9cec116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary'])[1]/preceding::span[2]</value>
      <webElementGuid>3b859bbc-07b2-44db-aab8-0658d65284bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secondary'])[1]/preceding::span[9]</value>
      <webElementGuid>f2dbabe6-9ba5-4928-8370-402c153902c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Records : 2']/parent::*</value>
      <webElementGuid>f22e4316-3fe3-4c60-97de-734c49d01748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//badge/span</value>
      <webElementGuid>585afa9e-4d18-47f9-a9bc-fdb395533368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'There are 2 records displayed in the grid below.' and (text() = 'Records : 2' or . = 'Records : 2')]</value>
      <webElementGuid>77e2d359-95ac-4028-8ffa-9324353a2251</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
