<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SNP(1)_k-icon ng-tns-c68-17 k-i-expand</name>
   <tag></tag>
   <elementGuidId>b6f54745-645b-4af4-ab1d-50cce9ef4a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//kendo-treeview[@id='mpweb-setup-options-list']/ul/li/ul/li[29]/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9c28a2e9-9ee7-4701-b7bb-e19db9a25ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon ng-tns-c68-17 k-i-expand</value>
      <webElementGuid>cdc38373-60a0-418a-941b-7287050b98c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-options-list&quot;)/ul[@class=&quot;k-treeview-lines ng-tns-c68-16 k-treeview-group ng-star-inserted&quot;]/li[@class=&quot;k-treeview-item ng-tns-c68-16 ng-star-inserted&quot;]/ul[@class=&quot;ng-tns-c68-17 ng-tns-c68-16 ng-trigger ng-trigger-toggle k-treeview-group ng-star-inserted&quot;]/li[@class=&quot;k-treeview-item ng-tns-c68-17 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c68-17 k-treeview-mid&quot;]/span[@class=&quot;k-treeview-toggle ng-tns-c68-17 ng-star-inserted&quot;]/span[@class=&quot;k-icon ng-tns-c68-17 k-i-expand&quot;]</value>
      <webElementGuid>dfbe8f20-7d56-474a-9991-d968e56da298</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-treeview[@id='mpweb-setup-options-list']/ul/li/ul/li[29]/div/span/span</value>
      <webElementGuid>fc285ae4-ac61-4aec-a870-40d6ecfce6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[29]/div/span/span</value>
      <webElementGuid>827a2206-45ac-419e-8247-9b4f8c3b2b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
