<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_user3</name>
   <tag></tag>
   <elementGuidId>3339d1ce-9c99-4b99-a251-a53099ddc8ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mpweb-setup-optionslist-item-a00065184870</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//kendo-treeview[@id='mpweb-setup-options-list']/ul/li/ul/li[29]/ul/li/div/span/span/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee271ca6-4dec-416d-ab5d-edac75180760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2aa02ae9-71c1-4fa8-a2aa-78238f3be99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inactiveClickable</value>
      <webElementGuid>4cb9aefb-f119-41ec-a2c5-cacc8d6cc340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-setup-optionslist-item-a00065184870</value>
      <webElementGuid>efde3e47-841d-4427-a87e-da91787171ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>user3 </value>
      <webElementGuid>3d7ca6e6-02f6-4da6-b2d1-d1fc72c86256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-optionslist-item-a00065184870&quot;)</value>
      <webElementGuid>baf3b970-0c19-4ce5-ab23-27b93af24dd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='mpweb-setup-optionslist-item-a00065184870']</value>
      <webElementGuid>465a2f89-a1f3-4d27-b046-04e8a42f41ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-treeview[@id='mpweb-setup-options-list']/ul/li/ul/li[29]/ul/li/div/span/span/div/span</value>
      <webElementGuid>df90c8ba-896e-42f4-9e2c-ccb3cb916d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='user3']/parent::*</value>
      <webElementGuid>22723955-10e8-4e1e-8df6-4e570e8c9829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[29]/ul/li/div/span/span/div/span</value>
      <webElementGuid>e17ee66e-23a2-4ff6-88cb-5d06bf8d2a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'mpweb-setup-optionslist-item-a00065184870' and (text() = 'user3 ' or . = 'user3 ')]</value>
      <webElementGuid>9feebc49-f3e7-42a2-9cd9-996111f624cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
