<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_user2</name>
   <tag></tag>
   <elementGuidId>1a1e5b7e-a4d1-4f32-82a4-6f6c44b7f445</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='user1'])[1]/following::span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mpweb-setup-optionslist-item-a00065185191</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>afc615ba-4636-4708-9f04-a643b57951d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d54d2d8-d893-4b31-9c84-1911e8794628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inactiveClickable</value>
      <webElementGuid>c2accaec-364d-4bc3-be6f-53e8314f432d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-setup-optionslist-item-a00065185191</value>
      <webElementGuid>9dc25dbd-b559-4af9-971b-69c6826ebc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>user2 </value>
      <webElementGuid>4e4f567b-45ec-42c6-939f-f212b4fd01e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-optionslist-item-a00065185191&quot;)</value>
      <webElementGuid>e6f77e2a-b5ad-4a63-b09e-6b346a4234ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='mpweb-setup-optionslist-item-a00065185191']</value>
      <webElementGuid>9c31081a-4e58-4426-ba30-bc24d92b6b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-treeview[@id='mpweb-setup-options-list']/ul/li/ul/li[29]/ul/li[2]/div/span/span/div/span</value>
      <webElementGuid>ba215410-25a3-4fb5-b1a6-db6aefa6eb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='user1'])[1]/following::span[3]</value>
      <webElementGuid>2d4eb897-423d-44ed-b2df-139350bb4266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='user3'])[1]/preceding::span[1]</value>
      <webElementGuid>57c86f54-b20a-40f7-960e-657b9ebea7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='user2']/parent::*</value>
      <webElementGuid>6938adae-8837-47be-b8ce-9776f18284e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[29]/ul/li[2]/div/span/span/div/span</value>
      <webElementGuid>b576a016-600a-49a1-9e8a-792fbfcb3dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'mpweb-setup-optionslist-item-a00065185191' and (text() = 'user2 ' or . = 'user2 ')]</value>
      <webElementGuid>76eef6b8-1060-4b2f-90cb-1a21931e776c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
