<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Log Out</name>
   <tag></tag>
   <elementGuidId>bf5d5f18-7f8a-4a7a-ac4f-a7557d1c9089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mpweb-navbar-login-dropdownlist']/a[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d077b930-8c5d-40fe-a893-adb7ac77bcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Log Out</value>
      <webElementGuid>81272e0f-5931-492a-91d0-7c17f01689d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-navbar-login-dropdownlist&quot;)/a[@class=&quot;dropdown-item&quot;]/span[1]</value>
      <webElementGuid>d8c3b23b-94e1-4e57-a600-acdbed4862ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mpweb-navbar-login-dropdownlist']/a[4]/span</value>
      <webElementGuid>8e2b7a05-b54a-42d3-9605-db2bb54f0dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last login: 12/27/2022 7:04:16 AM'])[1]/following::span[1]</value>
      <webElementGuid>ee6813d8-4bd1-40de-8c2d-ab992548a567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/following::span[1]</value>
      <webElementGuid>eecee4a4-a7bb-428e-88c9-f04f519adedd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/span</value>
      <webElementGuid>270609a8-d6a1-47e3-b1fe-634f614bf7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Log Out' or . = ' Log Out')]</value>
      <webElementGuid>8fa9c21c-81f7-42f1-8ea9-2410a4dfcba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
