<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_staff user (1)</name>
   <tag></tag>
   <elementGuidId>ceb60fde-a87e-4246-a633-7b9c7148699b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='mpweb-setup-optionslist-%26all_primary-staff+user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb69c604-f97b-493f-8d48-336cd82dd03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e244d4de-409b-46b1-a989-6ebcbc6b36e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>node-text</value>
      <webElementGuid>49902990-8ba6-4ade-81b9-74a9e1937837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>There is 1 Secondary item under this Primary</value>
      <webElementGuid>d8ac94ce-6d3c-44e6-af2e-e37344232950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpweb-setup-optionslist-%26all_primary-staff+user</value>
      <webElementGuid>51f0da6c-9880-486e-b22e-c9e2eb02e1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>staff user (1)</value>
      <webElementGuid>350708b5-3124-4158-9bc2-d7e23c36ecbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpweb-setup-optionslist-%26all_primary-staff+user&quot;)</value>
      <webElementGuid>755b1fd0-bf4d-4b64-99d2-ae1f859d6a64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='mpweb-setup-optionslist-%26all_primary-staff+user']</value>
      <webElementGuid>52d30a86-34b5-475b-af7c-6460599f9254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-treeview[@id='mpweb-setup-options-list']/ul/li/ul/li[29]/div/span[2]/span/div/span</value>
      <webElementGuid>55240cc3-188f-4663-9eb9-58c8349fd3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='staff user']/parent::*</value>
      <webElementGuid>160a9821-2099-43e9-a16f-ca3805a11936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[29]/div/span[2]/span/div/span</value>
      <webElementGuid>879f5881-f89f-44d4-828b-88a67edfdbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'There is 1 Secondary item under this Primary' and @id = 'mpweb-setup-optionslist-%26all_primary-staff+user' and (text() = 'staff user (1)' or . = 'staff user (1)')]</value>
      <webElementGuid>1366c824-1e24-4411-aadb-57ee20eadf6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
