<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password</name>
   <tag></tag>
   <elementGuidId>a1f84f69-86a7-4ef6-b6bc-e341d85d41bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mpauth-login-input-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mpauth-login-input-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98195304-59f6-4f0f-8b6f-b4e76a7ff788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group</value>
      <webElementGuid>45b2a296-21d9-445f-ac2b-5fb9fd23cff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mpauth-login-input-password</value>
      <webElementGuid>89b0c9a2-1005-4f42-9c97-fc566fd2f600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Password
                                    
                                </value>
      <webElementGuid>ea4d54d1-8ec3-4598-ae93-3253bb1d9d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpauth-login-input-password&quot;)</value>
      <webElementGuid>b32021a9-9e92-4797-9346-837116bdda8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mpauth-login-input-password']</value>
      <webElementGuid>bc36f519-1bc5-42a0-8c50-2b37814df612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::div[1]</value>
      <webElementGuid>f3407752-6ef6-42d5-8c64-b35a0d347c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MarketProminence Login'])[1]/following::div[3]</value>
      <webElementGuid>52c7ca3b-4b3d-4e2b-af8f-9cf56c2e5cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::div[1]</value>
      <webElementGuid>14d8caa4-f975-4a79-8216-131be3f22634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]</value>
      <webElementGuid>817aac22-101f-4963-86be-65ce37c42ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mpauth-login-input-password' and (text() = '
                                    Password
                                    
                                ' or . = '
                                    Password
                                    
                                ')]</value>
      <webElementGuid>26967be2-3bbd-4b30-98e2-034816c47b1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
