<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Secondary_secondary</name>
   <tag></tag>
   <elementGuidId>ffe0901b-ecb5-410d-b7fd-dda78a8d17cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-type-e7b72004-277f-43c5-bd7a-1b8f23bead2b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-type-e7b72004-277f-43c5-bd7a-1b8f23bead2b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0730d008-4d24-4609-a933-76f0ac209b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-input width-100-pct</value>
      <webElementGuid>88100c40-df8d-4138-8b0a-aeaf61e78758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-type-e7b72004-277f-43c5-bd7a-1b8f23bead2b</value>
      <webElementGuid>7fc853f8-087b-4fbe-aa5b-a546e31edc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>2f981150-0e0d-40fc-a5a8-92ac59135036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f73c5ff2-771f-4873-b03f-7eb5d85cfd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>db308b39-3361-401e-9bd4-b9fd373a14a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-type-e7b72004-277f-43c5-bd7a-1b8f23bead2b&quot;)</value>
      <webElementGuid>eaaa49e5-5045-489a-9e4f-bcda3876a2c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-type-e7b72004-277f-43c5-bd7a-1b8f23bead2b']</value>
      <webElementGuid>9619268d-b21d-4742-932c-f1670b9292cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mpweb-setup-setupaction-input-secondary']/input</value>
      <webElementGuid>f9987841-9b27-4b77-ba1f-eee1be14fb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>2e5bd046-7d34-4670-9cc0-85b6662c8329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-type-e7b72004-277f-43c5-bd7a-1b8f23bead2b' and @name = 'secondary' and @type = 'text']</value>
      <webElementGuid>fff6cb89-f560-495e-9e2a-53ce73aef785</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
