<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_EP03-1</name>
   <tag></tag>
   <elementGuidId>e43f2752-c15a-4f87-9c6d-63e6a6d6e620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='cbe35216-7df5-43ec-a40b-17423eac6e9c-EP03-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbe35216-7df5-43ec-a40b-17423eac6e9c-EP03-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c30d5e92-5b2c-444b-9e78-5c23dbae5d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cdbbb57e-ad15-4aeb-b486-4dcafa31bf51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item k-focus ng-star-inserted</value>
      <webElementGuid>d291c6b7-7ec3-4da5-a2f9-890bf7e74b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbe35216-7df5-43ec-a40b-17423eac6e9c-EP03-1</value>
      <webElementGuid>c9269382-ccb1-4aa3-adaf-5c7402d35e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>62de3ec3-fea9-44e5-9f51-4abf72dabe1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c7233460-c83f-4918-91d7-65443fe49aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EP03-1</value>
      <webElementGuid>0eda2779-1274-4fa4-80f6-3fc6c892a0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbe35216-7df5-43ec-a40b-17423eac6e9c-EP03-1&quot;)</value>
      <webElementGuid>407f7d7e-a7d0-4e9f-9737-d19a5a161428</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='cbe35216-7df5-43ec-a40b-17423eac6e9c-EP03-1']</value>
      <webElementGuid>c9ea39aa-8c58-49d8-b67f-68c356b257b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='33ab6628-b7aa-455f-803d-229c50baaa8a']/li</value>
      <webElementGuid>ba987ef8-5864-40be-9b68-953a68cc39b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WEB_SANDBOX DB Version 2021.3 Build 3602'])[1]/following::li[1]</value>
      <webElementGuid>69eb43f8-564e-4f66-8e58-2212ef84a533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 1996-2020 MedHOK, Inc.'])[1]/following::li[1]</value>
      <webElementGuid>2335fb89-0079-49d5-9dab-0aceb9eb7c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EP06-1'])[6]/preceding::li[1]</value>
      <webElementGuid>f736abd0-3cca-4b03-a94a-de93ae29c4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-list/div/ul/li</value>
      <webElementGuid>689d6eb3-97a8-4014-a5c4-45d7ec5d6ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'cbe35216-7df5-43ec-a40b-17423eac6e9c-EP03-1' and (text() = 'EP03-1' or . = 'EP03-1')]</value>
      <webElementGuid>9d8fc963-8ad4-40d3-89a4-94134c5a478d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
