<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_E05-3</name>
   <tag></tag>
   <elementGuidId>6dc135fe-5fda-4650-ad1f-436845c54e1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='4dcea6d6-1cef-4c87-8a99-f3a4980c22c4-E05-3']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4dcea6d6-1cef-4c87-8a99-f3a4980c22c4-E05-3 > span.template.text-overflow-ellipsis.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d3309620-e718-494d-bcac-d8f2080a0b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>template text-overflow-ellipsis ng-star-inserted</value>
      <webElementGuid>8a0e0401-f271-41e3-8c21-4d166d7e349f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>E05-3</value>
      <webElementGuid>57603e88-8a87-4d38-b63b-7229cac625ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E05-3</value>
      <webElementGuid>5b2be90e-123c-47a3-b07f-7ed5f74cbc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4dcea6d6-1cef-4c87-8a99-f3a4980c22c4-E05-3&quot;)/span[@class=&quot;template text-overflow-ellipsis ng-star-inserted&quot;]</value>
      <webElementGuid>87a8d437-665c-4071-8944-5720a7061327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='4dcea6d6-1cef-4c87-8a99-f3a4980c22c4-E05-3']/span</value>
      <webElementGuid>477b2604-77be-4800-a9ad-d6d326685ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E05-2'])[5]/following::span[1]</value>
      <webElementGuid>93896513-c98b-458e-9fea-268d0b7156fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E05-1'])[200]/following::span[2]</value>
      <webElementGuid>8790f6c1-cc4f-47d9-958d-c020b97b74ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E07-1'])[9]/preceding::span[1]</value>
      <webElementGuid>5a3bfe80-0c61-4b70-a9f0-88d43d916cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E07-10'])[3]/preceding::span[2]</value>
      <webElementGuid>316a3b4e-a9c9-4c14-938b-02071b147b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span</value>
      <webElementGuid>940d62da-819a-4ef2-9b48-1f5121ca22b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'E05-3' and (text() = 'E05-3' or . = 'E05-3')]</value>
      <webElementGuid>1042fba0-8af0-4d86-998b-87ac53aa257a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
