<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Program_k-input-value-text</name>
   <tag></tag>
   <elementGuidId>33bc064e-189c-4ce8-a4e2-64a2a4ed7743</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='c861c81f-aa25-494a-8ac5-03b9ac63cc72']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c861c81f-aa25-494a-8ac5-03b9ac63cc72 > span.k-input-value-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8e9be7ef-8447-46be-be0d-3e2a76878180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-value-text</value>
      <webElementGuid>ca104e16-4040-4f75-a806-90adf05d91b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c861c81f-aa25-494a-8ac5-03b9ac63cc72&quot;)/span[@class=&quot;k-input-value-text&quot;]</value>
      <webElementGuid>4edfaae8-6070-40eb-8b05-8d230503eda5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='c861c81f-aa25-494a-8ac5-03b9ac63cc72']/span</value>
      <webElementGuid>c2924d4c-0040-4b7b-9b81-f8fcdb4a4408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[3]/following::span[2]</value>
      <webElementGuid>53225306-4f1d-40b3-8e9d-207a11b42297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cortez, Andre'])[4]/following::span[2]</value>
      <webElementGuid>338906ea-b012-4a56-80bd-236e040a201f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary'])[2]/preceding::span[2]</value>
      <webElementGuid>0b84244d-b990-4dae-8c89-0fbb3e29c825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secondary'])[2]/preceding::span[3]</value>
      <webElementGuid>e9bdc999-7fa7-4191-92fa-50938caca4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/kendo-dropdownlist/span/span</value>
      <webElementGuid>ac319c59-c965-4920-a6fa-6b9cf79b96f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
